### ISSUE TITLE
Attempting to play "playlist" URL doesn't work.

### ISSUE THREAD

**Issue by snrgarb** [South-Paw/discord-music-bot#6]
I've attempted to debug the issue but can't trace it back. 

Here is the console output:

```
"Gabriel" (id: 126662078575542272 | group: admin) issued "/play https://www.youtube.com/playlist?list=PL9BCA60EEB1C8893D" | Running Command
```

**Comment by South-Paw** [comment]
Hi there! Playing from a playlist is not implemented yet - it's on the [project roadmap](https://github.com/South-Paw/discord-music-bot/projects/6) but I just haven't had time to get to it yet.

You can still use `!play` to play youtube URLs directly though and add them to the bots queue.

**Comment by snrgarb** [comment]
Haha no worries then.

**Comment by South-Paw** [comment]
All good - hopefully it'll be implemented soonish...
